name: deployment
run-name: ${{ github.actor }} is deploying the app
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: pull git repo
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            if [ -d .git ]; then
              cd ~/monetization
              git pull
            else
              cd ~
              git clone git@github.com:iradukundablaise/monetization.git
            fi